"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-03 20:30:26.255734
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "cancelled", name="batchstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_batches_created_at_status", ["created_at", "status"], unique=False
        )

    op.create_table(
        "raw_recordings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    with op.batch_alter_table("raw_recordings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_recordings_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_raw_recordings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_raw_recordings_expired_at"), ["expired_at"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recording_session", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("project", sa.String(length=128), nullable=True),
        sa.Column("agent", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("pane", sa.String(length=64), nullable=True),
        sa.Column("pane_name", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("risky_actions", sa.JSON(), nullable=False),
        sa.Column("files_touched", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("raw_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["raw_id"], ["raw_recordings.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recording_session"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_agent"), ["agent"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_model"), ["model"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_project"), ["project"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_started_at"), ["started_at"], unique=False)

    op.create_table(
        "batch_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "failed", "cancelled", name="itemstatus"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("not_before", sa.DateTime(), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_retryable", sa.Boolean(), nullable=True),
        sa.Column("raw_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["raw_id"], ["raw_recordings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batch_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_batch_items_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index(
            "ix_batch_items_status_not_before", ["status", "not_before"], unique=False
        )

    op.create_table(
        "enrichments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("frustration", sa.Float(), nullable=False),
        sa.Column("stuck_points", sa.JSON(), nullable=False),
        sa.Column("prompt_feedback", sa.Text(), nullable=True),
        sa.Column("model_fit", sa.String(length=16), nullable=True),
        sa.Column("model_fit_reason", sa.Text(), nullable=True),
        sa.Column("risk_notes", sa.JSON(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    with op.batch_alter_table("enrichments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_enrichments_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_enrichments_outcome"), ["outcome"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("enrichments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_enrichments_outcome"))
        batch_op.drop_index(batch_op.f("ix_enrichments_category"))

    op.drop_table("enrichments")
    with op.batch_alter_table("batch_items", schema=None) as batch_op:
        batch_op.drop_index("ix_batch_items_status_not_before")
        batch_op.drop_index(batch_op.f("ix_batch_items_batch_id"))

    op.drop_table("batch_items")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_started_at"))
        batch_op.drop_index(batch_op.f("ix_sessions_project"))
        batch_op.drop_index(batch_op.f("ix_sessions_model"))
        batch_op.drop_index(batch_op.f("ix_sessions_agent"))

    op.drop_table("sessions")
    with op.batch_alter_table("raw_recordings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_recordings_expired_at"))
        batch_op.drop_index(batch_op.f("ix_raw_recordings_created_at"))
        batch_op.drop_index(batch_op.f("ix_raw_recordings_content_hash"))

    op.drop_table("raw_recordings")
    with op.batch_alter_table("batches", schema=None) as batch_op:
        batch_op.drop_index("ix_batches_created_at_status")

    op.drop_table("batches")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
